ARG PHP_VERSION
FROM php:${PHP_VERSION}-cli-alpine

ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /var/www/html

RUN apk add --upgrade xz # Fix CVE-2022-32207 xz security
RUN apk add --upgrade curl # Fix CVE-2022-32207 curl security
RUN apk add --upgrade openssl # Fix CVE-2021-3711 openssl security

# persistent / runtime deps
RUN curl -sSLf \
        -o /usr/local/bin/install-php-extensions \
        https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
    chmod +x /usr/local/bin/install-php-extensions

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Copy configuration
COPY config/php-cli.ini /usr/local/etc/php/conf.d/

RUN echo "expose_php = Off" > /usr/local/etc/php/conf.d/expose_php.ini

# Install extensions
RUN install-php-extensions @composer
RUN install-php-extensions opcache sysvsem soap intl gettext ldap swoole zip
RUN install-php-extensions amqp mongodb redis mysqli pgsql pdo_mysql pdo_pgsql
RUN install-php-extensions gd imagick exif

RUN apk add --no-cache gnu-libiconv && \
    apk add --no-cache libwebp-tools jpegoptim optipng pngquant && \
    apk add --no-cache mysql-client

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php