# syntax=docker/dockerfile:1
ARG PHP_VERSION
ARG IMAGE_VARIANT
ARG NODE_VERSION
FROM node:${NODE_VERSION}-alpine AS node
FROM adeliom/php:${PHP_VERSION}-${IMAGE_VARIANT}

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin
COPY --from=node /opt /opt