# syntax=docker/dockerfile:1
ARG PHP_VERSION
ARG REGISTRY
ARG TAG_VERSION
FROM ${REGISTRY}/php:${PHP_VERSION}-frankenphp${TAG_VERSION:''}

LABEL org.opencontainers.image.source=https://github.com/agence-adeliom/docker-images/tree/main/php
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.authors="Adeliom https://adeliom.com"
LABEL org.opencontainers.image.title="PHP ${PHP_VERSION} - FrankenPHP - wkhtmltopdf"
LABEL org.opencontainers.image.description="PHP ${PHP_VERSION} Docker image with FrankenPHP and wkhtmltopdf"

RUN set -x \
    && apt-get update \
    && apt-get install -y \
        wkhtmltopdf \
        imagemagick \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
