# syntax=docker/dockerfile:1
ARG PHP_VERSION
FROM adeliom/php:${PHP_VERSION}-frankenphp

RUN set -x \
    && apt-get update \
    && apt-get install -y \
        wkhtmltopdf \
        imagemagick \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
