name: CI

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: docker.io
  PREFIX: arnaudritti

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    outputs:
      REGISTRY: ${{ steps.docker-env.outputs.REGISTRY }}
      PREFIX: ${{ steps.docker-env.outputs.PREFIX }}   
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Print inputs passed to the reusable workflow
        id: docker-env
        run: |
          echo "::set-output name=REGISTRY::$REGISTRY"
          echo "::set-output name=PREFIX::$PREFIX"

  build-php-images:
    uses: ./.github/workflows/build_php.yml
    needs: [docker-setup]
    secrets: inherit
    with:
      image: php
      prefix: ${{ needs.docker-setup.outputs.PREFIX }}
      registry: ${{ needs.docker-setup.outputs.REGISTRY }}

  dockerhub-php-doc:
    runs-on: ubuntu-latest
    needs: [build-php-images]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ needs.build-php-images.outputs.repository }}
          readme-filepath: ./php/README.md