name: ci

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_PREFIX: arnaudritti

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-php-images:
    runs-on: ubuntu-latest
    needs: docker-setup
    strategy:
      fail-fast: false
      matrix:
          image: ["php"]
          version: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2.0RC2"]
          variant: [cli, fpm, caddy, fpm-wkhtmltopdf, caddy-wkhtmltopdf]
          platforms: ["linux/amd64,linux/arm64"]
    steps:
      - name: Set image tag
        run: echo '::set-output name=IMAGE_TAG::$IMAGE_PREFIX/${{ matrix.image }}:${{ matrix.version }}-${{ matrix.variant }}'
        id: image_tag
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image }}
          file: Dockerfile.${{ matrix.variant }}
          load: true
          tags: ${{ steps.image_tag.outputs.IMAGE_TAG }}
          build-args: |
            PHP_VERSION=${{ matrix.version }}
      -
        name: Test
        run: |
          docker run --rm ${{ steps.image_tag.outputs.IMAGE_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ steps.image_tag.outputs.IMAGE_TAG }}
          build-args: |
            PHP_VERSION=${{ matrix.version }}

  dockerhub-php-images:
    runs-on: ubuntu-latest
    needs: build-php-images
    strategy:
      fail-fast: false
    steps:
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: $IMAGE_PREFIX/php
          readme-filepath: ./php/README.md