name: CI

on: 
  schedule:
    - cron: 0 6 * * 1,4
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.filter.outputs.php }}
      phpdoc: ${{ steps.filter.outputs.phpdoc }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            php:
              - '.github/workflows/build_php.yml'
              - 'php/config/**'
              - 'php/Dockerfile.*'
            phpdoc:
              - 'php/*.md'

  build-php-images:
    needs: changes
    if: ${{ needs.changes.outputs.php == 'true' }}
    uses: ./.github/workflows/build_php.yml
    secrets: inherit
    with:
      image: php
      registry: adeliom

  dockerhub-php-doc:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.phpdoc == 'true' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adeliom/php
          readme-filepath: ./php/README.md