name: Auto release (github package)

on:
#  schedule:
#    - cron: 0 6 * * 1,4
  release:
    types: [ published ]

jobs:

  build-php-images:
    uses: ./.github/workflows/build_php.yml
    secrets: inherit
    with:
      image: php
      registry: adeliom
      generate_dev: false

  dockerhub-php-doc:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adeliom/php
          readme-filepath: ./php/README.md
